# Generated by Django 5.1.1 on 2024-10-25 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apphome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type_formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='apphome.typeformation')),
            ],
        ),
        migrations.AddField(
            model_name='thematique',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thematiques', to='apphome.categorie'),
        ),
    ]
