# Generated by Django 5.1.1 on 2024-10-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apphome', '0002_categorie_thematique_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='code',
            field=models.CharField(default='', editable=False, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='thematique',
            name='code_prefix',
            field=models.CharField(default='', max_length=10),
        ),
    ]
