# Generated by Django 5.1.1 on 2024-10-25 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apphome', '0003_formation_code_thematique_code_prefix'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoyenPeda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Prerequis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PublicCible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_quoi', models.TextField(help_text="Qu'est-ce que la formation ?")),
                ('description_pourquoi', models.TextField(help_text='Pourquoi se certifier ?')),
                ('objectifs', models.TextField(help_text='Objectifs de la formation')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programmes', to='apphome.formation')),
                ('moyens_peda', models.ManyToManyField(blank=True, to='apphome.moyenpeda')),
                ('prerequis', models.ManyToManyField(blank=True, to='apphome.prerequis')),
                ('public_cible', models.ManyToManyField(blank=True, to='apphome.publiccible')),
            ],
        ),
        migrations.CreateModel(
            name='Objectif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.CharField(max_length=200)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectif', to='apphome.programme')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('ordre', models.PositiveIntegerField(default=1)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='apphome.programme')),
            ],
        ),
    ]
