# Generated by Django 5.1.1 on 2024-10-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apphome', '0004_moyenpeda_prerequis_publiccible_programme_objectif_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeformation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='type_formation_images/'),
        ),
    ]
