# Generated by Django 5.1.1 on 2024-10-30 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apphome', '0007_newslettersubscriber_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thematique',
            name='description',
        ),
        migrations.RemoveField(
            model_name='typeformation',
            name='description',
        ),
        migrations.AlterField(
            model_name='thematique',
            name='code_prefix',
            field=models.CharField(default='', max_length=3),
        ),
    ]
