# Generated by Django 5.1.1 on 2024-10-30 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apphome', '0008_remove_thematique_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formation',
            name='description',
        ),
    ]
