# Generated by Django 5.1.1 on 2024-10-31 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apphome', '0009_remove_formation_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='inclus',
            field=models.TextField(blank=True, help_text='Éléments inclus dans la formation'),
        ),
    ]
