# Generated by Django 5.1.1 on 2024-10-31 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apphome', '0010_programme_inclus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='programme',
        ),
        migrations.AddField(
            model_name='programme',
            name='modules',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='apphome.module'),
        ),
    ]
