# Generated by Django 5.1.1 on 2024-10-31 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apphome', '0011_remove_module_programme_programme_modules'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='module',
            name='nom',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='technique',
            field=models.ManyToManyField(blank=True, to='apphome.technique'),
        ),
    ]
