# Generated by Django 5.1.1 on 2024-10-31 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apphome', '0013_remove_module_technique_module_techniques_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='titre',
        ),
    ]
