# Generated by Django 5.1.1 on 2024-10-31 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apphome', '0014_remove_module_titre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programme',
            name='modules',
        ),
        migrations.AddField(
            model_name='module',
            name='programme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='apphome.programme'),
        ),
    ]
