# Generated by Django 5.1.1 on 2024-10-31 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apphome', '0015_remove_programme_modules_module_programme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='programme',
        ),
        migrations.AddField(
            model_name='programme',
            name='modules',
            field=models.ManyToManyField(blank=True, related_name='programmes', to='apphome.module'),
        ),
    ]
