# Generated by Django 5.1.1 on 2024-10-31 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apphome', '0017_remove_programme_modules_module_programme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='techniques',
        ),
        migrations.AddField(
            model_name='technique',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='techniques', to='apphome.module'),
        ),
    ]
