# Generated by Django 5.1.1 on 2024-10-31 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apphome', '0018_remove_module_techniques_technique_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='techniques_brutes',
            field=models.TextField(blank=True, help_text='Entrez chaque technique sur une ligne séparée'),
        ),
        migrations.AlterField(
            model_name='module',
            name='programme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='apphome.programme'),
        ),
    ]
