# Generated by Django 5.1.1 on 2024-10-31 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apphome', '0019_module_techniques_brutes_alter_module_programme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programme',
            name='moyens_peda',
        ),
        migrations.RemoveField(
            model_name='programme',
            name='prerequis',
        ),
        migrations.RemoveField(
            model_name='programme',
            name='public_cible',
        ),
        migrations.DeleteModel(
            name='Objectif',
        ),
        migrations.AddField(
            model_name='programme',
            name='moyens_peda',
            field=models.TextField(help_text='Entrez chaque moyen pédagogique sur une nouvelle ligne', null=True, verbose_name='Moyens pédagogiques'),
        ),
        migrations.AddField(
            model_name='programme',
            name='prerequis',
            field=models.TextField(help_text='Entrez chaque prérequis sur une nouvelle ligne', null=True, verbose_name='Prérequis'),
        ),
        migrations.AddField(
            model_name='programme',
            name='public_cible',
            field=models.TextField(help_text='Entrez chaque public cible sur une nouvelle ligne', null=True, verbose_name='Public Cible'),
        ),
    ]
