# Generated by Django 5.1.1 on 2025-01-30 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apphome', '0021_delete_moyenpeda_delete_prerequis_delete_publiccible'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='formations/'),
        ),
    ]
