# Generated by Django 5.1.1 on 2025-01-30 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apphome', '0022_formation_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newslettersubscriber',
            name='password',
        ),
    ]
